name: Publish NPM Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Tag Version
        run: npm version ${{github.event.release.tag_name}} --no-git-tag-version
      - name: Install Package
        run: npm ci
      - name: Build Package
        run: npm run build
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Commit Version
        env:
          VERSION: ${{github.event.release.tag_name}}
        run: |
          git config --global user.name 'lol-plus-bot'
          git commit -a -m "release: $VERSION"
